# примеры API-запросов

@baseUrl = http://localhost:5000

# создание пользователя
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "User_1",
  "email": "user1@gmail.ru",
  "password": "87654321"
}

###

# получение токена
POST {{baseUrl}}/login
Content-Type: application/json

{
  "name": "User_1",
  "password": "87654321"
}

###

# получение данных по токену пользователя
GET {{baseUrl}}/user
Authorization: 384089c3-67fb-47b4-aad0-e20da6a378f4

###

# обновление пользователя по токену
PATCH {{baseUrl}}/user
Content-Type: application/json
Authorization: 384089c3-67fb-47b4-aad0-e20da6a378f4

{
  "email": "email@mail.ru",
  "password": "12345678"
}

###

# удаление пользователя по токену
DELETE {{baseUrl}}/user
Content-Type: application/json
Authorization: 3de65cf9-e2d8-4c06-a4d8-94a38b69ae51

###

# подача объявления
POST {{baseUrl}}/ads
Content-Type: application/json
Authorization: 74a505e6-fcad-4602-a99d-0811870af191

{
  "title": "Title",
  "description": "text ads 111"
}

###

# все объявления
GET {{baseUrl}}/ads
Content-Type: application/json

###

# поиск объявления по id
GET {{baseUrl}}/ads/1
Content-Type: application/json

###

# обновление объявления
PATCH {{baseUrl}}/ads/1
Content-Type: application/json; charset=utf-8
Authorization: 384089c3-67fb-47b4-aad0-e20da6a378f4

{
  "title": "Ads",
  "description": "text"
}

###

# удаление объявления
DELETE {{baseUrl}}/ads/1
Content-Type: application/json; charset=utf-8
Authorization: 384089c3-67fb-47b4-aad0-e20da6a378f4

###